### ISSUE TITLE
Feature request: Config 'ignore_self', separated for info and messages

### ISSUE THREAD

**Issue by sirrated** [Murturtle/MeshLink#9]
Feature request to selectively ignore meshlink node messages, based on info/telemetry vs. Primary Channel messages.

Telemetry/Info messages from 'self' or the node connected to Meshlink are numerous, typically every minute.  Enabling these messages ad-hoc assists with debugging, but normally should be disabled.

Messages to the Primary Channel are useful to see for Discord users. When nodes use the bot commands, the Meshlink node response is only seen in the mesh.  Discord users only see one side of the 'conversation'. A separate config option would allow these messages to be enabled selectively.

Thank you for all the great work!

**Comment by Murturtle** [comment]
makes sense I will try to add this

**Comment by Murturtle** [comment]
@sirrated check the latest version out and tell me if thats what you mean.

**Comment by sirrated** [comment]
Two minor syntax errors in MeshLink.py, preventing it from running:
Line 219: if(config["send_mesh_commands_to_discord"]:
Line 219: if(config["send_mesh_commands_to_discord"]):

Line 229: final_message+=genUserName(interface,packet)+" > "+str(packet["decoded"]["portnum"]
Line 229: final_message+=genUserName(interface,packet)+" > "+str(packet["decoded"]["portnum"])

I sent a '!time' command from a node. The MeshLink monitor responded with the current UTC time, but the response was only seen in the mesh, not in Discord.

**Comment by Murturtle** [comment]
shall i close this issue?

**Comment by sirrated** [comment]
New feature is working as requested. No other syntax errors found. Thank you!  This issue is closed.
